server:
  port: 6568
  
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test
    username: root
    password: mysql.ks18@@
    
  jpa:
    hibernate:
      ddl-auto: update
      
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl


#  application:
#    name: pagingandsorting
